---
# language: bash
language: python
python:
  - "2.7"
services: docker

env:
  - distro: fedora29

script:
  # Download test shim.
  # - mkdir -p ${PWD}/tests
  - curl -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: studioservers:qgnyZ3JoXis7CHgZ7eIAmuP8
