---
- name: install docker packages
  package:
    name: "{{ item }}"
  with_items:
    - docker
    - docker-compose
    - docker-machine

- name: create the docker group
  group:
    name: docker
    state: present

- name: add user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: true

- name: enable docker service
  service:
    name: docker
    enabled: true
    state: started
