---
- name: Enabling extra Repositories
  become: true
  become_user: root
  dnf:
    name: "{{ pkg }}"
    state: latest
- name: installing python and deps for ansible modules.
  raw: dnf install -y python2 python2-dnf libselinux-python

- name: Update the system.
  become: true
  become_user: root
  dnf:
    name: "*"
    state: latest
